//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.31 at 09:48:19 PM CST 
//


package mx.gob.sat.esquemas.contabilidade._1_1.catalogocuentas;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.gob.sat.esquemas.contabilidade._1_1.catalogocuentas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.gob.sat.esquemas.contabilidade._1_1.catalogocuentas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Catalogo.Ctas }
     * 
     */
    public Catalogo.Ctas createCatalogoCtas() {
        return new Catalogo.Ctas();
    }

    /**
     * Create an instance of {@link Catalogo }
     * 
     */
    public Catalogo createCatalogo() {
        return new Catalogo();
    }

}
