//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.31 at 09:48:19 PM CST 
//

@XmlSchema(
        namespace = "http://www.sat.gob.mx/esquemas/ContabilidadE/1_1/CatalogoCuentas", 
        xmlns = {
            @XmlNs(namespaceURI = "http://www.sat.gob.mx/esquemas/ContabilidadE/1_1/CatalogoCuentas", prefix = "catalogocuentas"),
            @XmlNs(namespaceURI = "http://www.w3.org/2001/XMLSchema-instance", prefix = "xsi")
        },
        elementFormDefault = XmlNsForm.QUALIFIED
        
    )
package mx.gob.sat.esquemas.contabilidade._1_1.catalogocuentas;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;

