version: '3.6'

x-shared-environment: &commonEnv
    TZ: "America/Mexico_City"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
    POSTGRES_PORT: 5432
    POSTGRES_HOST: "rdbms_dos"
    POSTGRES_DB: "erp"
    MYSQL_ROOT_PASSWORD: "mysql"
    MYSQL_DATABASE: "dwh"
    AWS_FAC_PROFILE: "fac-cloudw"
    AWS_FAC_BUCKET: "cfdi-datalake-medica"

services:
    cache_erp:
        container_name: 'cache_erp'
        image: redis:alpine
        ports:
          - "6379:6379"
        environment: *commonEnv
        networks:
          - operational_network
    sso_erp:
        container_name: 'sso_erp'
        build: './DOS/sso'
        ports:
          - '10100:10100'
        environment: *commonEnv
        volumes:
          - ./DOS/keys:/pem
        networks:
          - operational_network
    rdbms_dos:
        container_name: 'rdbms_dos'
        image: 'debezium/postgres'
        ports:
          - '5432:5432'
        environment: *commonEnv
        volumes:
          - rdbms_dos_data:/var/lib/postgresql/data
        networks:
          - operational_network
    rdbms_staging:
        image: 'mysql:5'
        container_name: 'rdbms_staging'
        ports:
          - '3306:3306'
        environment: *commonEnv
        volumes:
          - rdbms_staging_data:/var/lib/mysql
          - ./DWH/scripts:/scripts
          - ./DWH/migrations:/migrations
        networks:
          - operational_network
    sales_api:
        container_name: 'sales_api'
        build: './DOS/sales-api'
        ports:
          - '10090:10090'
        environment: *commonEnv
        volumes:
          - ~/.aws:/root/.aws
        networks:
          - operational_network
    cfdiengine:
        container_name: 'cfdiengine'
        build: './DOS/cfdiengine'
        volumes:
          - '${ERP_ROOT}/resources:/resources'
        ports:
          - '10080:10080'
        environment: *commonEnv
        networks:
          - operational_network
    cobranza_api:
        container_name: 'cobranza_api'
        build: './DOS/cobranza-api'
        ports:
          - '10110:10110'
        environment: *commonEnv
        networks:
          - operational_network


networks:
    operational_network:
        name: operational_network
        driver: bridge

volumes:
    rdbms_staging_data:
    rdbms_dos_data:
