STAGE=${STAGE:-"$HOME"}

export SALES_GRPC_HOST="127.0.0.1"
export SALES_GRPC_PORT="10090"
export COBRANZA_GRPC_HOST="127.0.0.1"
export COBRANZA_GRPC_PORT="10110"

TIME_STAMP_BUILD=$(date +%s)

export BINDIR="$STAGE/$TIME_STAMP_BUILD/out"
export RELDIR="$STAGE/$TIME_STAMP_BUILD/release"

[ -d $BINDIR ] || mkdir -p $BINDIR
[ -d $RELDIR ] || mkdir -p $RELDIR
