//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.21 at 08:38:02 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "www.sat.gob.mx/esquemas/ContabilidadE/1_1/BalanzaComprobacion", 
        xmlns = {
            @XmlNs(namespaceURI = "www.sat.gob.mx/esquemas/ContabilidadE/1_1/BalanzaComprobacion", prefix = "BCE"),
            @XmlNs(namespaceURI = "http://www.w3.org/2001/XMLSchema-instance", prefix = "xsi")
        },
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED
        )
package mx.gob.sat.esquemas.contabilidade._1_1.balanzacomprobacion;

import javax.xml.bind.annotation.XmlNs;

